spring.application.name=spring-la-mia-pizzeria-crud

# Data source
spring.datasource.url=jdbc:mysql://localhost:3306/pizzeria_db
spring.datasource.username=root
spring.datasource.password=R00troot

# Hibernate properties
# The SQL dialect make Hibernate generate bettere SQL for the choosen database 
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto(none, create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Informazioni aggiuntive utili per il testing (da rimuovere)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.jpa.generate-ddl=true
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# server.port=8080