INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Margherita', 'Pomodoro, Mozzarella, Basilico', 6.50, 'https://example.com/margherita.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Marinara', 'Pomodoro, Aglio, Origano', 5.50, 'https://example.com/marinara.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Diavola', 'Pomodoro, Mozzarella, Salame piccante', 7.50, 'https://example.com/diavola.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Quattro Formaggi', 'Mozzarella, Gorgonzola, Fontina, Parmigiano', 8.50, 'https://example.com/quattro-formaggi.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Capricciosa', 'Pomodoro, Mozzarella, Prosciutto cotto, Funghi, Carciofi, Olive', 8.00, 'https://example.com/capricciosa.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Quattro Stagioni', 'Pomodoro, Mozzarella, Prosciutto cotto, Funghi, Carciofi, Olive', 8.00, 'https://example.com/quattro-stagioni.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Bufalina', 'Pomodoro, Mozzarella di Bufala, Basilico', 8.50, 'https://example.com/bufalina.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Prosciutto e Funghi', 'Pomodoro, Mozzarella, Prosciutto cotto, Funghi', 7.50, 'https://example.com/prosciutto-funghi.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Romana', 'Pomodoro, Mozzarella, Acciughe, Capperi, Origano', 7.00, 'https://example.com/romana.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Napoletana', 'Pomodoro, Mozzarella, Acciughe, Capperi, Olive', 7.50, 'https://example.com/napoletana.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Vegetariana', 'Pomodoro, Mozzarella, Zucchine, Melanzane, Peperoni', 7.50, 'https://example.com/vegetariana.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Tonno e Cipolla', 'Pomodoro, Mozzarella, Tonno, Cipolla', 7.50, 'https://example.com/tonno-cipolla.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Salsiccia e Friarielli', 'Mozzarella, Salsiccia, Friarielli', 8.50, 'https://example.com/salsiccia-friarielli.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Americana', 'Pomodoro, Mozzarella, Würstel, Patatine', 7.50, 'https://example.com/americana.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Boscaiola', 'Pomodoro, Mozzarella, Funghi, Salsiccia', 8.00, 'https://example.com/boscaiola.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Zucchine e Speck', 'Mozzarella, Zucchine, Speck', 8.00, 'https://example.com/zucchine-speck.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Gorgonzola e Noci', 'Mozzarella, Gorgonzola, Noci', 8.50, 'https://example.com/gorgonzola-noci.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Crudo e Rucola', 'Pomodoro, Mozzarella, Prosciutto crudo, Rucola', 8.50, 'https://example.com/crudo-rucola.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Focaccia', 'Olio extravergine di oliva, Sale, Rosmarino', 5.00, 'https://example.com/focaccia.jpg');
INSERT INTO pizze (name, pizza_ingredient, price, url) VALUES ('Calzone Classico', 'Pomodoro, Mozzarella, Prosciutto cotto, Funghi', 8.00, 'https://example.com/calzone.jpg');